<?php

namespace Database\Seeders;

use App\Models\KnowledgeBaseArticle;
use App\Models\KnowledgeBaseCategory;
use Illuminate\Database\Seeder;

class KnowledgeBaseSeeder extends Seeder
{
    public function run(): void
    {
        $category = KnowledgeBaseCategory::updateOrCreate(
            ['slug' => 'monitoring-checks'],
            [
                'name' => [
                    'en' => 'Monitoring Checks',
                    'uk' => 'Перевірки моніторингу',
                    'pl' => 'Sprawdzenia monitorowania',
                ],
                'description' => [
                    'en' => 'Learn how each monitoring check works and what it detects.',
                    'uk' => 'Дізнайтеся, як працює кожна перевірка та що вона виявляє.',
                    'pl' => 'Dowiedz się, jak działa każde sprawdzenie monitorowania i co wykrywa.',
                ],
                'sort_order' => 1,
            ]
        );

        $articles = [
            [
                'slug' => 'http-status-check',
                'sort_order' => 1,
                'title' => [
                    'en' => 'HTTP Status Check',
                    'uk' => 'Перевірка HTTP-статусу',
                    'pl' => 'Sprawdzenie statusu HTTP',
                ],
                'excerpt' => [
                    'en' => 'Verifies that your website returns a successful HTTP response code, confirming it is reachable and online.',
                    'uk' => 'Перевіряє, що ваш сайт повертає успішний HTTP-код відповіді, підтверджуючи його доступність.',
                    'pl' => 'Weryfikuje, czy Twoja strona zwraca poprawny kod odpowiedzi HTTP, potwierdzając jej dostępność.',
                ],
                'content' => [
                    'en' => '<h2>What is HTTP?</h2><p>HTTP (HyperText Transfer Protocol) is the foundation of data communication on the web. Every time a browser loads a page, it sends an HTTP request to a server, and the server replies with a response that includes a <strong>status code</strong> — a three-digit number indicating whether the request succeeded, failed, or needs further action.</p><p>HTTP was originally defined in <a href="https://www.rfc-editor.org/rfc/rfc1945" target="_blank" rel="noopener">RFC 1945</a> (HTTP/1.0) and evolved through <a href="https://www.rfc-editor.org/rfc/rfc9110" target="_blank" rel="noopener">RFC 9110</a> (HTTP Semantics, the current standard).</p><h2>What is an HTTP Status Check?</h2><p>An HTTP status check sends a request to your website and evaluates the response code returned by the server. A successful response (2xx) means the site is up; codes like 4xx or 5xx indicate problems.</p><h2>Common Status Codes</h2><ul><li><strong>200 OK</strong> — The page loaded successfully.</li><li><strong>301/302</strong> — Redirect. DigiPulse follows redirects automatically.</li><li><strong>404 Not Found</strong> — The page does not exist.</li><li><strong>500 Internal Server Error</strong> — The server encountered an error.</li><li><strong>503 Service Unavailable</strong> — The server is temporarily down or overloaded.</li></ul><h2>Why It Matters</h2><p>This is the most fundamental check. It detects outages instantly and is the fastest check available. Use it as the baseline for every site you monitor.</p><h2>Further Reading</h2><ul><li><a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Status" target="_blank" rel="noopener">MDN Web Docs — HTTP response status codes</a></li><li><a href="https://www.rfc-editor.org/rfc/rfc9110#section-15" target="_blank" rel="noopener">RFC 9110 §15 — Status Codes</a></li><li><a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview" target="_blank" rel="noopener">MDN Web Docs — An overview of HTTP</a></li></ul>',
                    'uk' => '<h2>Що таке HTTP?</h2><p>HTTP (HyperText Transfer Protocol) — це основа передачі даних в інтернеті. Кожного разу, коли браузер завантажує сторінку, він надсилає HTTP-запит до сервера, а сервер відповідає відповіддю, що містить <strong>код статусу</strong> — тризначне число, яке вказує на успіх, помилку або необхідність подальших дій.</p><p>HTTP спочатку був визначений у <a href="https://www.rfc-editor.org/rfc/rfc1945" target="_blank" rel="noopener">RFC 1945</a> (HTTP/1.0) і еволюціонував до <a href="https://www.rfc-editor.org/rfc/rfc9110" target="_blank" rel="noopener">RFC 9110</a> (поточний стандарт).</p><h2>Що таке перевірка HTTP-статусу?</h2><p>Перевірка HTTP-статусу надсилає запит до вашого сайту та оцінює код відповіді сервера. Успішна відповідь (2xx) означає, що сайт працює; коди 4xx або 5xx вказують на проблеми.</p><h2>Поширені коди статусу</h2><ul><li><strong>200 OK</strong> — Сторінка завантажена успішно.</li><li><strong>301/302</strong> — Перенаправлення. DigiPulse автоматично слідкує за ними.</li><li><strong>404 Not Found</strong> — Сторінка не існує.</li><li><strong>500 Internal Server Error</strong> — Сервер зіткнувся з помилкою.</li><li><strong>503 Service Unavailable</strong> — Сервер тимчасово недоступний або перевантажений.</li></ul><h2>Чому це важливо</h2><p>Це найбазовіша перевірка. Вона миттєво виявляє збої і є найшвидшою з доступних. Використовуйте її як основу для кожного сайту, що ви моніторите.</p><h2>Додаткове читання</h2><ul><li><a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Status" target="_blank" rel="noopener">MDN Web Docs — Коди статусу HTTP</a></li><li><a href="https://www.rfc-editor.org/rfc/rfc9110#section-15" target="_blank" rel="noopener">RFC 9110 §15 — Status Codes</a></li><li><a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview" target="_blank" rel="noopener">MDN Web Docs — Огляд HTTP</a></li></ul>',
                    'pl' => '<h2>Czym jest HTTP?</h2><p>HTTP (HyperText Transfer Protocol) to podstawa komunikacji danych w internecie. Za każdym razem, gdy przeglądarka ładuje stronę, wysyła żądanie HTTP do serwera, a serwer odpowiada odpowiedzią zawierającą <strong>kod statusu</strong> — trzycyfrową liczbę wskazującą, czy żądanie się powiodło, nie powiodło lub wymaga dalszego działania.</p><p>HTTP został pierwotnie zdefiniowany w <a href="https://www.rfc-editor.org/rfc/rfc1945" target="_blank" rel="noopener">RFC 1945</a> (HTTP/1.0) i ewoluował do <a href="https://www.rfc-editor.org/rfc/rfc9110" target="_blank" rel="noopener">RFC 9110</a> (aktualny standard).</p><h2>Czym jest sprawdzenie statusu HTTP?</h2><p>Sprawdzenie statusu HTTP wysyła żądanie do Twojej strony i ocenia kod odpowiedzi zwrócony przez serwer. Pomyślna odpowiedź (2xx) oznacza, że strona działa; kody 4xx lub 5xx wskazują na problemy.</p><h2>Popularne kody statusu</h2><ul><li><strong>200 OK</strong> — Strona załadowana pomyślnie.</li><li><strong>301/302</strong> — Przekierowanie. DigiPulse automatycznie podąża za przekierowaniami.</li><li><strong>404 Not Found</strong> — Strona nie istnieje.</li><li><strong>500 Internal Server Error</strong> — Serwer napotkał błąd.</li><li><strong>503 Service Unavailable</strong> — Serwer jest tymczasowo niedostępny lub przeciążony.</li></ul><h2>Dlaczego to ważne</h2><p>To najbardziej podstawowe sprawdzenie. Wykrywa awarie natychmiastowo i jest najszybszym dostępnym sprawdzeniem. Używaj go jako podstawy dla każdej monitorowanej strony.</p><h2>Dodatkowe materiały</h2><ul><li><a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Status" target="_blank" rel="noopener">MDN Web Docs — Kody statusu HTTP</a></li><li><a href="https://www.rfc-editor.org/rfc/rfc9110#section-15" target="_blank" rel="noopener">RFC 9110 §15 — Status Codes</a></li><li><a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview" target="_blank" rel="noopener">MDN Web Docs — Przegląd HTTP</a></li></ul>',
                ],
            ],
            [
                'slug' => 'ssl-certificate-monitoring',
                'sort_order' => 2,
                'title' => [
                    'en' => 'SSL Certificate Monitoring',
                    'uk' => 'Моніторинг SSL-сертифіката',
                    'pl' => 'Monitorowanie certyfikatu SSL',
                ],
                'excerpt' => [
                    'en' => 'Monitors your SSL certificate validity and warns you before it expires, preventing browser warnings and loss of trust.',
                    'uk' => 'Відстежує дійсність SSL-сертифіката та попереджає про закінчення терміну дії, запобігаючи попередженням браузера.',
                    'pl' => 'Monitoruje ważność certyfikatu SSL i ostrzega przed jego wygaśnięciem, zapobiegając ostrzeżeniom przeglądarki.',
                ],
                'content' => [
                    'en' => '<h2>What is TLS/SSL?</h2><p>TLS (Transport Layer Security), often still called SSL (Secure Sockets Layer), is a cryptographic protocol that provides encrypted communication between a client and a server. When you see <strong>HTTPS</strong> in a browser\'s address bar and a padlock icon, TLS is at work.</p><p>A TLS certificate is issued by a trusted Certificate Authority (CA) and contains the domain name, public key, issuer, and expiration date. The current standard is TLS 1.3, defined in <a href="https://www.rfc-editor.org/rfc/rfc8446" target="_blank" rel="noopener">RFC 8446</a>. The older SSL name persists colloquially, but SSL 3.0 and all prior versions are deprecated and insecure.</p><h2>What is SSL Certificate Monitoring?</h2><p>SSL certificate monitoring checks whether your site\'s certificate is valid, trusted, and not about to expire. An expired certificate causes browsers to show security warnings, immediately driving visitors away.</p><h2>What DigiPulse Checks</h2><ul><li><strong>Expiration date</strong> — Alerts you 30, 14, and 7 days before expiry.</li><li><strong>Chain validity</strong> — Ensures the full certificate chain is trusted.</li><li><strong>Domain match</strong> — Confirms the certificate covers the monitored domain.</li></ul><h2>Why It Matters</h2><p>Even a single hour with an expired certificate can damage user trust and affect your search engine ranking. Automated monitoring ensures you never miss a renewal deadline.</p><h2>Further Reading</h2><ul><li><a href="https://letsencrypt.org/how-it-works/" target="_blank" rel="noopener">Let\'s Encrypt — How It Works</a></li><li><a href="https://www.rfc-editor.org/rfc/rfc8446" target="_blank" rel="noopener">RFC 8446 — TLS 1.3</a></li><li><a href="https://developer.mozilla.org/en-US/docs/Web/Security/Transport_Layer_Security" target="_blank" rel="noopener">MDN Web Docs — Transport Layer Security</a></li><li><a href="https://www.cloudflare.com/learning/ssl/what-is-ssl/" target="_blank" rel="noopener">Cloudflare — What is SSL?</a></li></ul>',
                    'uk' => '<h2>Що таке TLS/SSL?</h2><p>TLS (Transport Layer Security), який часто досі називають SSL (Secure Sockets Layer) — це криптографічний протокол, що забезпечує зашифровану комунікацію між клієнтом і сервером. Коли в адресному рядку браузера ви бачите <strong>HTTPS</strong> і значок замка — це TLS у дії.</p><p>Сертифікат TLS видається довіреним центром сертифікації (CA) і містить доменне ім\'я, публічний ключ, видавця та дату закінчення. Поточний стандарт — TLS 1.3, визначений у <a href="https://www.rfc-editor.org/rfc/rfc8446" target="_blank" rel="noopener">RFC 8446</a>. Стара назва SSL збереглася в побуті, але SSL 3.0 та всі попередні версії застаріли та є небезпечними.</p><h2>Що таке моніторинг SSL-сертифіката?</h2><p>Моніторинг SSL-сертифіката перевіряє, чи дійсний, довірений та не близький до закінчення сертифікат вашого сайту. Прострочений сертифікат змушує браузери показувати попередження безпеки, відлякуючи відвідувачів.</p><h2>Що перевіряє DigiPulse</h2><ul><li><strong>Дата закінчення</strong> — Сповіщає за 30, 14 і 7 днів до закінчення терміну.</li><li><strong>Дійсність ланцюжка</strong> — Гарантує, що повний ланцюжок сертифікатів є довіреним.</li><li><strong>Відповідність домену</strong> — Підтверджує, що сертифікат охоплює відстежуваний домен.</li></ul><h2>Чому це важливо</h2><p>Навіть одна година з простроченим сертифікатом може підірвати довіру користувачів і вплинути на рейтинг у пошукових системах. Автоматизований моніторинг гарантує, що ви ніколи не пропустите дедлайн поновлення.</p><h2>Додаткове читання</h2><ul><li><a href="https://letsencrypt.org/how-it-works/" target="_blank" rel="noopener">Let\'s Encrypt — Як це працює</a></li><li><a href="https://www.rfc-editor.org/rfc/rfc8446" target="_blank" rel="noopener">RFC 8446 — TLS 1.3</a></li><li><a href="https://developer.mozilla.org/en-US/docs/Web/Security/Transport_Layer_Security" target="_blank" rel="noopener">MDN Web Docs — Transport Layer Security</a></li><li><a href="https://www.cloudflare.com/learning/ssl/what-is-ssl/" target="_blank" rel="noopener">Cloudflare — Що таке SSL?</a></li></ul>',
                    'pl' => '<h2>Czym jest TLS/SSL?</h2><p>TLS (Transport Layer Security), często wciąż nazywany SSL (Secure Sockets Layer), to protokół kryptograficzny zapewniający szyfrowaną komunikację między klientem a serwerem. Gdy widzisz <strong>HTTPS</strong> w pasku adresu przeglądarki i ikonę kłódki — TLS jest w działaniu.</p><p>Certyfikat TLS jest wydawany przez zaufany Urząd Certyfikacji (CA) i zawiera nazwę domeny, klucz publiczny, wystawcę i datę wygaśnięcia. Aktualnym standardem jest TLS 1.3, zdefiniowany w <a href="https://www.rfc-editor.org/rfc/rfc8446" target="_blank" rel="noopener">RFC 8446</a>. Stara nazwa SSL utrzymała się potocznie, ale SSL 3.0 i wszystkie wcześniejsze wersje są przestarzałe i niebezpieczne.</p><h2>Czym jest monitorowanie certyfikatu SSL?</h2><p>Monitorowanie certyfikatu SSL sprawdza, czy certyfikat Twojej strony jest ważny, zaufany i nie wygasa wkrótce. Wygasły certyfikat powoduje, że przeglądarki wyświetlają ostrzeżenia bezpieczeństwa, natychmiast odstraszając odwiedzających.</p><h2>Co sprawdza DigiPulse</h2><ul><li><strong>Data wygaśnięcia</strong> — Ostrzega 30, 14 i 7 dni przed wygaśnięciem.</li><li><strong>Ważność łańcucha</strong> — Zapewnia, że pełny łańcuch certyfikatów jest zaufany.</li><li><strong>Dopasowanie domeny</strong> — Potwierdza, że certyfikat obejmuje monitorowaną domenę.</li></ul><h2>Dlaczego to ważne</h2><p>Nawet jedna godzina z wygasłym certyfikatem może zaszkodzić zaufaniu użytkowników i wpłynąć na pozycję w wyszukiwarkach. Automatyczne monitorowanie zapewnia, że nigdy nie przegapisz terminu odnowienia.</p><h2>Dodatkowe materiały</h2><ul><li><a href="https://letsencrypt.org/how-it-works/" target="_blank" rel="noopener">Let\'s Encrypt — Jak to działa</a></li><li><a href="https://www.rfc-editor.org/rfc/rfc8446" target="_blank" rel="noopener">RFC 8446 — TLS 1.3</a></li><li><a href="https://developer.mozilla.org/en-US/docs/Web/Security/Transport_Layer_Security" target="_blank" rel="noopener">MDN Web Docs — Transport Layer Security</a></li><li><a href="https://www.cloudflare.com/learning/ssl/what-is-ssl/" target="_blank" rel="noopener">Cloudflare — Czym jest SSL?</a></li></ul>',
                ],
            ],
            [
                'slug' => 'dns-check',
                'sort_order' => 3,
                'title' => [
                    'en' => 'DNS Check',
                    'uk' => 'Перевірка DNS',
                    'pl' => 'Sprawdzenie DNS',
                ],
                'excerpt' => [
                    'en' => 'Ensures your domain name resolves correctly to an IP address, detecting DNS misconfigurations and propagation issues.',
                    'uk' => 'Гарантує правильне розпізнавання доменного імені до IP-адреси, виявляючи помилки DNS та проблеми поширення.',
                    'pl' => 'Zapewnia, że nazwa domeny rozwiązuje się poprawnie do adresu IP, wykrywając błędy DNS i problemy propagacji.',
                ],
                'content' => [
                    'en' => '<h2>What is DNS?</h2><p>The Domain Name System (DNS) is often described as the internet\'s phone book. It is a hierarchical, distributed database that translates human-readable domain names (like <code>example.com</code>) into machine-readable IP addresses (like <code>93.184.216.34</code>) that routers and servers use to direct traffic.</p><p>DNS was originally specified in <a href="https://www.rfc-editor.org/rfc/rfc1034" target="_blank" rel="noopener">RFC 1034</a> and <a href="https://www.rfc-editor.org/rfc/rfc1035" target="_blank" rel="noopener">RFC 1035</a>. Every time you visit a website, your device queries a DNS resolver which walks the hierarchy — from root servers, to TLD servers, to authoritative nameservers — to find the answer.</p><h2>What is a DNS Check?</h2><p>A DNS check verifies that your domain resolves correctly to a valid IP address. It queries an authoritative nameserver directly, independent of your web server, so it catches DNS-level failures that other checks would miss.</p><h2>What DigiPulse Checks</h2><ul><li><strong>Domain resolution</strong> — Confirms your domain resolves to a valid IP address.</li><li><strong>Response time</strong> — Measures how fast DNS lookup completes.</li><li><strong>Failure detection</strong> — Alerts you if the domain becomes unresolvable.</li></ul><h2>Why It Matters</h2><p>DNS failures mean no one can reach your site, even if your server is perfectly healthy. Issues can arise from expired domains, misconfigured records, or DNS provider outages. This check catches those problems independently of your web server.</p><h2>Further Reading</h2><ul><li><a href="https://www.cloudflare.com/learning/dns/what-is-dns/" target="_blank" rel="noopener">Cloudflare — What is DNS?</a></li><li><a href="https://www.rfc-editor.org/rfc/rfc1035" target="_blank" rel="noopener">RFC 1035 — Domain Names: Implementation and Specification</a></li><li><a href="https://developer.mozilla.org/en-US/docs/Glossary/DNS" target="_blank" rel="noopener">MDN Web Docs — DNS</a></li><li><a href="https://www.iana.org/domains/root" target="_blank" rel="noopener">IANA — Root Zone Management</a></li></ul>',
                    'uk' => '<h2>Що таке DNS?</h2><p>DNS (система доменних імен) часто описується як телефонна книга інтернету. Це ієрархічна розподілена база даних, яка перекладає зрозумілі людині доменні імена (як <code>example.com</code>) в машинно-зрозумілі IP-адреси (як <code>93.184.216.34</code>), які маршрутизатори та сервери використовують для спрямування трафіку.</p><p>DNS спочатку був визначений у <a href="https://www.rfc-editor.org/rfc/rfc1034" target="_blank" rel="noopener">RFC 1034</a> та <a href="https://www.rfc-editor.org/rfc/rfc1035" target="_blank" rel="noopener">RFC 1035</a>. Кожного разу, коли ви відвідуєте сайт, ваш пристрій запитує DNS-резолвер, який проходить ієрархію — від кореневих серверів до серверів TLD і авторитативних серверів імен — щоб знайти відповідь.</p><h2>Що таке перевірка DNS?</h2><p>Перевірка DNS підтверджує правильність розпізнавання вашого домену до дійсної IP-адреси. Вона запитує авторитативний сервер імен безпосередньо, незалежно від вашого веб-сервера, тому виявляє збої на рівні DNS, які інші перевірки пропустили б.</p><h2>Що перевіряє DigiPulse</h2><ul><li><strong>Розпізнавання домену</strong> — Підтверджує, що ваш домен розпізнається до дійсної IP-адреси.</li><li><strong>Час відповіді</strong> — Вимірює швидкість виконання DNS-запиту.</li><li><strong>Виявлення збоїв</strong> — Сповіщає, якщо домен перестає розпізнаватися.</li></ul><h2>Чому це важливо</h2><p>Збої DNS означають, що ніхто не може потрапити на ваш сайт, навіть якщо сервер працює ідеально. Проблеми можуть виникнути через прострочені домени, неправильні записи або збої провайдера DNS.</p><h2>Додаткове читання</h2><ul><li><a href="https://www.cloudflare.com/learning/dns/what-is-dns/" target="_blank" rel="noopener">Cloudflare — Що таке DNS?</a></li><li><a href="https://www.rfc-editor.org/rfc/rfc1035" target="_blank" rel="noopener">RFC 1035 — Доменні імена: реалізація та специфікація</a></li><li><a href="https://developer.mozilla.org/en-US/docs/Glossary/DNS" target="_blank" rel="noopener">MDN Web Docs — DNS</a></li><li><a href="https://www.iana.org/domains/root" target="_blank" rel="noopener">IANA — Управління кореневою зоною</a></li></ul>',
                    'pl' => '<h2>Czym jest DNS?</h2><p>System nazw domenowych (DNS) jest często opisywany jako książka telefoniczna internetu. To hierarchiczna, rozproszona baza danych, która tłumaczy czytelne dla człowieka nazwy domen (jak <code>example.com</code>) na adresy IP (jak <code>93.184.216.34</code>) używane przez routery i serwery do kierowania ruchu.</p><p>DNS został pierwotnie określony w <a href="https://www.rfc-editor.org/rfc/rfc1034" target="_blank" rel="noopener">RFC 1034</a> i <a href="https://www.rfc-editor.org/rfc/rfc1035" target="_blank" rel="noopener">RFC 1035</a>. Za każdym razem, gdy odwiedzasz stronę, Twoje urządzenie wysyła zapytanie do resolwera DNS, który przechodzi hierarchię — od serwerów głównych, przez serwery TLD, do autorytatywnych serwerów nazw — aby znaleźć odpowiedź.</p><h2>Czym jest sprawdzenie DNS?</h2><p>Sprawdzenie DNS weryfikuje, czy domena rozwiązuje się poprawnie do prawidłowego adresu IP. Wysyła zapytanie bezpośrednio do autorytatywnego serwera nazw, niezależnie od serwera WWW, wykrywając awarie na poziomie DNS, które inne sprawdzenia by przeoczyły.</p><h2>Co sprawdza DigiPulse</h2><ul><li><strong>Rozwiązywanie domeny</strong> — Potwierdza, że domena rozwiązuje się do prawidłowego adresu IP.</li><li><strong>Czas odpowiedzi</strong> — Mierzy szybkość wykonania zapytania DNS.</li><li><strong>Wykrywanie awarii</strong> — Ostrzega, jeśli domena przestaje się rozwiązywać.</li></ul><h2>Dlaczego to ważne</h2><p>Awarie DNS oznaczają, że nikt nie może dotrzeć do Twojej strony, nawet jeśli serwer działa idealnie. Problemy mogą wynikać z wygasłych domen, błędnie skonfigurowanych rekordów lub awarii dostawcy DNS.</p><h2>Dodatkowe materiały</h2><ul><li><a href="https://www.cloudflare.com/learning/dns/what-is-dns/" target="_blank" rel="noopener">Cloudflare — Czym jest DNS?</a></li><li><a href="https://www.rfc-editor.org/rfc/rfc1035" target="_blank" rel="noopener">RFC 1035 — Nazwy domen: implementacja i specyfikacja</a></li><li><a href="https://developer.mozilla.org/en-US/docs/Glossary/DNS" target="_blank" rel="noopener">MDN Web Docs — DNS</a></li><li><a href="https://www.iana.org/domains/root" target="_blank" rel="noopener">IANA — Zarządzanie strefą główną</a></li></ul>',
                ],
            ],
            [
                'slug' => 'port-check',
                'sort_order' => 4,
                'title' => [
                    'en' => 'Port Check',
                    'uk' => 'Перевірка порту',
                    'pl' => 'Sprawdzenie portu',
                ],
                'excerpt' => [
                    'en' => 'Verifies that a specific TCP port is open and reachable on your server, useful for monitoring any network service.',
                    'uk' => 'Перевіряє, чи відкритий та доступний певний TCP-порт на вашому сервері — корисно для моніторингу будь-якого мережевого сервісу.',
                    'pl' => 'Weryfikuje, czy określony port TCP jest otwarty i dostępny na serwerze — przydatne do monitorowania dowolnej usługi sieciowej.',
                ],
                'content' => [
                    'en' => '<h2>What are TCP Ports?</h2><p>A TCP port is a logical endpoint for network communication. While an IP address identifies a machine on a network, a port number identifies a specific process or service running on that machine. TCP (Transmission Control Protocol) uses port numbers (0–65535) to multiplex connections — letting one server run dozens of services simultaneously.</p><p>Well-known ports (0–1023) are assigned by <a href="https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml" target="_blank" rel="noopener">IANA</a> to standard services. TCP itself is defined in <a href="https://www.rfc-editor.org/rfc/rfc9293" target="_blank" rel="noopener">RFC 9293</a>.</p><h2>What is a Port Check?</h2><p>A port check attempts to establish a TCP connection to a specific port on your server. This verifies not just that the server is reachable, but that a specific service is listening and accepting connections.</p><h2>Common Ports to Monitor</h2><ul><li><strong>80</strong> — HTTP web traffic</li><li><strong>443</strong> — HTTPS web traffic</li><li><strong>22</strong> — SSH access</li><li><strong>3306</strong> — MySQL database</li><li><strong>5432</strong> — PostgreSQL database</li><li><strong>25 / 587</strong> — Email (SMTP)</li></ul><h2>Why It Matters</h2><p>A web server may be running while a critical background service has crashed. Port checks let you monitor individual services independently, giving you a granular view of your infrastructure health.</p><h2>Further Reading</h2><ul><li><a href="https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml" target="_blank" rel="noopener">IANA — Service Name and Transport Protocol Port Number Registry</a></li><li><a href="https://www.rfc-editor.org/rfc/rfc9293" target="_blank" rel="noopener">RFC 9293 — Transmission Control Protocol (TCP)</a></li><li><a href="https://www.cloudflare.com/learning/network-layer/what-is-a-computer-port/" target="_blank" rel="noopener">Cloudflare — What is a computer port?</a></li></ul>',
                    'uk' => '<h2>Що таке TCP-порти?</h2><p>TCP-порт — це логічна точка мережевого зв\'язку. Якщо IP-адреса ідентифікує машину в мережі, то номер порту ідентифікує конкретний процес або сервіс, що працює на цій машині. TCP (Transmission Control Protocol) використовує номери портів (0–65535) для мультиплексування з\'єднань — дозволяючи одному серверу одночасно запускати десятки сервісів.</p><p>Відомі порти (0–1023) призначені <a href="https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml" target="_blank" rel="noopener">IANA</a> стандартним сервісам. Сам TCP визначений у <a href="https://www.rfc-editor.org/rfc/rfc9293" target="_blank" rel="noopener">RFC 9293</a>.</p><h2>Що таке перевірка порту?</h2><p>Перевірка порту намагається встановити TCP-з\'єднання з певним портом вашого сервера. Це підтверджує не лише доступність сервера, а й те, що конкретний сервіс слухає та приймає з\'єднання.</p><h2>Поширені порти для моніторингу</h2><ul><li><strong>80</strong> — HTTP-трафік</li><li><strong>443</strong> — HTTPS-трафік</li><li><strong>22</strong> — SSH-доступ</li><li><strong>3306</strong> — База даних MySQL</li><li><strong>5432</strong> — База даних PostgreSQL</li><li><strong>25 / 587</strong> — Електронна пошта (SMTP)</li></ul><h2>Чому це важливо</h2><p>Веб-сервер може працювати, тоді як критичний фоновий сервіс вийшов з ладу. Перевірки портів дозволяють незалежно моніторити окремі сервіси, надаючи детальне уявлення про стан інфраструктури.</p><h2>Додаткове читання</h2><ul><li><a href="https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml" target="_blank" rel="noopener">IANA — Реєстр портів і назв сервісів</a></li><li><a href="https://www.rfc-editor.org/rfc/rfc9293" target="_blank" rel="noopener">RFC 9293 — Transmission Control Protocol (TCP)</a></li><li><a href="https://www.cloudflare.com/learning/network-layer/what-is-a-computer-port/" target="_blank" rel="noopener">Cloudflare — Що таке комп\'ютерний порт?</a></li></ul>',
                    'pl' => '<h2>Czym są porty TCP?</h2><p>Port TCP to logiczny punkt końcowy komunikacji sieciowej. Podczas gdy adres IP identyfikuje maszynę w sieci, numer portu identyfikuje konkretny proces lub usługę działającą na tej maszynie. TCP (Transmission Control Protocol) używa numerów portów (0–65535) do multipleksowania połączeń — pozwalając jednemu serwerowi jednocześnie uruchamiać dziesiątki usług.</p><p>Dobrze znane porty (0–1023) są przypisane przez <a href="https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml" target="_blank" rel="noopener">IANA</a> do standardowych usług. Sam TCP jest zdefiniowany w <a href="https://www.rfc-editor.org/rfc/rfc9293" target="_blank" rel="noopener">RFC 9293</a>.</p><h2>Czym jest sprawdzenie portu?</h2><p>Sprawdzenie portu próbuje nawiązać połączenie TCP z określonym portem na serwerze. Weryfikuje to nie tylko, że serwer jest osiągalny, ale że konkretna usługa nasłuchuje i akceptuje połączenia.</p><h2>Popularne porty do monitorowania</h2><ul><li><strong>80</strong> — Ruch HTTP</li><li><strong>443</strong> — Ruch HTTPS</li><li><strong>22</strong> — Dostęp SSH</li><li><strong>3306</strong> — Baza danych MySQL</li><li><strong>5432</strong> — Baza danych PostgreSQL</li><li><strong>25 / 587</strong> — Poczta elektroniczna (SMTP)</li></ul><h2>Dlaczego to ważne</h2><p>Serwer WWW może działać, podczas gdy krytyczna usługa w tle uległa awarii. Sprawdzenia portów pozwalają niezależnie monitorować poszczególne usługi, dając szczegółowy wgląd w kondycję infrastruktury.</p><h2>Dodatkowe materiały</h2><ul><li><a href="https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml" target="_blank" rel="noopener">IANA — Rejestr portów i nazw usług</a></li><li><a href="https://www.rfc-editor.org/rfc/rfc9293" target="_blank" rel="noopener">RFC 9293 — Transmission Control Protocol (TCP)</a></li><li><a href="https://www.cloudflare.com/learning/network-layer/what-is-a-computer-port/" target="_blank" rel="noopener">Cloudflare — Czym jest port komputerowy?</a></li></ul>',
                ],
            ],
            [
                'slug' => 'icmp-ping',
                'sort_order' => 5,
                'title' => [
                    'en' => 'ICMP Ping',
                    'uk' => 'ICMP Ping',
                    'pl' => 'ICMP Ping',
                ],
                'excerpt' => [
                    'en' => 'Measures network latency and server reachability using ICMP ping, the most basic indicator of server availability.',
                    'uk' => 'Вимірює мережеву затримку та доступність сервера за допомогою ICMP ping — найбазовішого індикатора доступності сервера.',
                    'pl' => 'Mierzy opóźnienie sieci i dostępność serwera za pomocą ICMP ping — najbardziej podstawowego wskaźnika dostępności serwera.',
                ],
                'content' => [
                    'en' => '<h2>What is ICMP?</h2><p>ICMP (Internet Control Message Protocol) is a network-layer protocol used by network devices to send error messages and operational information. Unlike TCP or UDP, ICMP is not used to exchange data between systems — it is a diagnostic and control protocol.</p><p>The most familiar ICMP operation is the <strong>echo request / echo reply</strong> pair, commonly known as "ping". When you run <code>ping example.com</code>, your machine sends an ICMP Echo Request packet; if the destination is reachable, it responds with an ICMP Echo Reply. The round-trip time is the <em>latency</em>. ICMP is defined in <a href="https://www.rfc-editor.org/rfc/rfc792" target="_blank" rel="noopener">RFC 792</a>; its IPv6 counterpart ICMPv6 is in <a href="https://www.rfc-editor.org/rfc/rfc4443" target="_blank" rel="noopener">RFC 4443</a>.</p><h2>What is an ICMP Ping Check?</h2><p>DigiPulse sends ICMP Echo Request packets to your server from our monitoring nodes and measures the round-trip time and packet loss. This is a network-level check — it tells you whether the server is reachable at the IP layer, regardless of what applications are running.</p><h2>What DigiPulse Measures</h2><ul><li><strong>Latency (ms)</strong> — Round-trip time from our monitoring node to your server.</li><li><strong>Packet loss</strong> — Percentage of ping packets that did not receive a response.</li><li><strong>Reachability</strong> — Whether the server responds at all.</li></ul><h2>Why It Matters</h2><p>A ping check detects network-level issues that other checks might miss — such as routing problems or network saturation. High latency often precedes a full outage, making this an early warning signal for infrastructure problems.</p><h2>Further Reading</h2><ul><li><a href="https://www.rfc-editor.org/rfc/rfc792" target="_blank" rel="noopener">RFC 792 — Internet Control Message Protocol</a></li><li><a href="https://www.cloudflare.com/learning/network-layer/internet-control-message-protocol-icmp/" target="_blank" rel="noopener">Cloudflare — What is ICMP?</a></li><li><a href="https://www.rfc-editor.org/rfc/rfc4443" target="_blank" rel="noopener">RFC 4443 — ICMPv6</a></li></ul>',
                    'uk' => '<h2>Що таке ICMP?</h2><p>ICMP (Internet Control Message Protocol) — це мережевий протокол, що використовується мережевими пристроями для надсилання повідомлень про помилки та операційної інформації. На відміну від TCP або UDP, ICMP не призначений для обміну даними між системами — це діагностичний і керуючий протокол.</p><p>Найбільш відома операція ICMP — пара <strong>echo request / echo reply</strong>, відома як "ping". Коли ви виконуєте <code>ping example.com</code>, ваш комп\'ютер надсилає пакет ICMP Echo Request; якщо адресат доступний, він відповідає ICMP Echo Reply. Час туди й назад — це <em>затримка</em>. ICMP визначений у <a href="https://www.rfc-editor.org/rfc/rfc792" target="_blank" rel="noopener">RFC 792</a>; аналог для IPv6 — ICMPv6 у <a href="https://www.rfc-editor.org/rfc/rfc4443" target="_blank" rel="noopener">RFC 4443</a>.</p><h2>Що таке перевірка ICMP Ping?</h2><p>DigiPulse надсилає пакети ICMP Echo Request на ваш сервер з наших вузлів моніторингу та вимірює час відповіді і втрату пакетів. Це перевірка на мережевому рівні — вона показує, чи доступний сервер на рівні IP, незалежно від запущених застосунків.</p><h2>Що вимірює DigiPulse</h2><ul><li><strong>Затримка (мс)</strong> — Час туди й назад від нашого вузла моніторингу до вашого сервера.</li><li><strong>Втрата пакетів</strong> — Відсоток ping-пакетів, які не отримали відповіді.</li><li><strong>Доступність</strong> — Чи відповідає сервер взагалі.</li></ul><h2>Чому це важливо</h2><p>Перевірка ping виявляє проблеми на мережевому рівні, які інші перевірки можуть пропустити — наприклад, проблеми з маршрутизацією або перевантаження мережі. Висока затримка часто передує повному збою.</p><h2>Додаткове читання</h2><ul><li><a href="https://www.rfc-editor.org/rfc/rfc792" target="_blank" rel="noopener">RFC 792 — Internet Control Message Protocol</a></li><li><a href="https://www.cloudflare.com/learning/network-layer/internet-control-message-protocol-icmp/" target="_blank" rel="noopener">Cloudflare — Що таке ICMP?</a></li><li><a href="https://www.rfc-editor.org/rfc/rfc4443" target="_blank" rel="noopener">RFC 4443 — ICMPv6</a></li></ul>',
                    'pl' => '<h2>Czym jest ICMP?</h2><p>ICMP (Internet Control Message Protocol) to protokół warstwy sieciowej używany przez urządzenia sieciowe do wysyłania komunikatów o błędach i informacji operacyjnych. W przeciwieństwie do TCP lub UDP, ICMP nie służy do wymiany danych między systemami — jest to protokół diagnostyczny i kontrolny.</p><p>Najbardziej znana operacja ICMP to para <strong>echo request / echo reply</strong>, powszechnie znana jako "ping". Gdy uruchamiasz <code>ping example.com</code>, Twoja maszyna wysyła pakiet ICMP Echo Request; jeśli cel jest osiągalny, odpowiada ICMP Echo Reply. Czas podróży w obie strony to <em>opóźnienie</em>. ICMP jest zdefiniowany w <a href="https://www.rfc-editor.org/rfc/rfc792" target="_blank" rel="noopener">RFC 792</a>; jego odpowiednik dla IPv6 — ICMPv6 — w <a href="https://www.rfc-editor.org/rfc/rfc4443" target="_blank" rel="noopener">RFC 4443</a>.</p><h2>Czym jest sprawdzenie ICMP Ping?</h2><p>DigiPulse wysyła pakiety ICMP Echo Request do Twojego serwera z naszych węzłów monitorowania i mierzy czas podróży oraz utratę pakietów. To sprawdzenie na poziomie sieci — mówi, czy serwer jest osiągalny w warstwie IP, niezależnie od uruchomionych aplikacji.</p><h2>Co mierzy DigiPulse</h2><ul><li><strong>Opóźnienie (ms)</strong> — Czas podróży w obie strony od naszego węzła monitorowania do Twojego serwera.</li><li><strong>Utrata pakietów</strong> — Procent pakietów ping, które nie otrzymały odpowiedzi.</li><li><strong>Dostępność</strong> — Czy serwer w ogóle odpowiada.</li></ul><h2>Dlaczego to ważne</h2><p>Sprawdzenie ping wykrywa problemy na poziomie sieci, które inne sprawdzenia mogą przeoczyć — takie jak problemy z routingiem lub nasycenie sieci. Wysokie opóźnienie często poprzedza pełną awarię.</p><h2>Dodatkowe materiały</h2><ul><li><a href="https://www.rfc-editor.org/rfc/rfc792" target="_blank" rel="noopener">RFC 792 — Internet Control Message Protocol</a></li><li><a href="https://www.cloudflare.com/learning/network-layer/internet-control-message-protocol-icmp/" target="_blank" rel="noopener">Cloudflare — Czym jest ICMP?</a></li><li><a href="https://www.rfc-editor.org/rfc/rfc4443" target="_blank" rel="noopener">RFC 4443 — ICMPv6</a></li></ul>',
                ],
            ],
        ];

        foreach ($articles as $data) {
            KnowledgeBaseArticle::updateOrCreate(
                ['slug' => $data['slug']],
                [
                    'knowledge_base_category_id' => $category->id,
                    'title' => $data['title'],
                    'excerpt' => $data['excerpt'],
                    'content' => $data['content'],
                    'sort_order' => $data['sort_order'],
                    'published_at' => now(),
                ]
            );
        }
    }
}
